---
title: 'Chapter 3'
author: "melody"
date: "2020/3/18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## packages

```{r}
library(googlesheets4)
```

```{r}
a <- 2
a = 2 # = 與 <-同義
3 -> b
```

```{r}
a+b
```


```{r}
my_108_total_credits <- 15
_108_total_credits <- 15
108_total_credits <- 15
_my_108_total_credits <- 15
my.108.total_credits <- 15
.108.total_credits <- 15 # 隱藏變數
.my.108.total_credits <- 15
我的108學年總學分數 <- 15
`我的108學年總學分數` <- 15 # 特殊名稱處理，`不是名稱的一部份
`.108.total_credits` <- 15
```


## calling an object
```{r}
a <- 15 # 變數設定
b <- a # 呼叫a的值，用來設定變數b的值，相當於 b <- 15
```

```{r}
`我的年紀` <- 21
my_age = `我的年紀`
```

## Atomic vector

## Numeric
```{r}
num1 <- 5
vNum1 <- c(2,5)
vNum2 <- c(2, num1)
```

```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum3 <- c(vNum1,vNum2)
vNum4 <- c(-1,5,2,3)
vNum5 <- c(c(-1,5),c(2,3))
```

```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum4 <- c() # 空向量
```

```{r}
vNum3 <- c(vNum2, vNum1)
vNum4 <- c(vNum4, vNum1) # 向量疊代 （recursive vector concatenate）
```

```{r}
num1<-5 # 非整數
num2<-5L # 整數

num1Vector<-c(5,6,7)
num2Vector<-c(5L,6L,7L)
```

```{r}
char1<-"你好"
char2<-'你好'
```

```{r}
char1Vector<-c("你好","How are you?")
```

```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
```

```{r}
library(httr)
library(dplyr)
GET("https://api.github.com/repos/MelodyLin0106/108-2-56-inclass-practice/commits") %>%
  content() %>%
  View()
```

```{r}
library(googlesheets4)
`出席狀況表單網址` <- "https://docs.google.com/spreadsheets/d/1oB-5hj1pO5g8FMpZbA7RgIG8NvCRx6WvLPwvleCEV4Q/edit#gid=987577191" # 缺乏定義值，要加雙引號變成字串
ss <- as_sheets_id(`出席狀況表單網址`)
homework_sheet <- sheets_read(ss,sheet=1)
```

```{r}
logi1 <- c(T,TRUE,F,FALSE,FALSE)
```

```{r}
# 加總向量內的所有元素值。
sum(logi1)
```

```{r}
num <- c(1.5, 2, 3)
int <- c(1L, 3L, -2L)
char <- c("1.5","2","3")
logi <- c(T,T,F)

typeof(num)
typeof(int)
typeof(char)
typeof(logi)
```

