---
title: "2020-04-15"
author: "pei"
date: "2020/4/19"
output: html_document
---

##### list應用{-}

```{r}
vector1 <- c(a=1,b=3,c=4)
vector1[["a"]]
vector1[c("a","c")]
vector1$`a`  # 不能執行，只有list可以用$選取

list1 <- list(a=1,b=3,c=4)
list1[["a"]]
list1[c("a","c")]
list1$`a`
```


今明兩日台北市、新北市氣溫：
```{r}
today <- list(
  list("台北市",c(highest_temp = 25),c(lowest_temp = 18)),
  list("新北市",c(highest_temp = 24),c(lowest_temp = 15)))
str(today)
```

```{r}
today <- list(
  list("台北市",
       highest_temp=c(highest_temp = 25),
       lowest_temp=c(lowest_temp = 18)),
  list("新北市",
       highest_temp=c(highest_temp = 24),
       lowest_temp=c(lowest_temp = 15)))
str(today)
```

```{r}
today[[1]]$highest_temp
```


```{r}
tomorrow <- list(
  list("台北市",
       highest_temp=c(highest_temp = 25),
       lowest_temp=c(lowest_temp = 18)),
  list("新北市",
       highest_temp=c(highest_temp = 24),
       lowest_temp=c(lowest_temp = 15)))

weather <- list(today,tomorrow)

print(weather)
```

```{r}
weather[[1]][[2]][[2]] # 今天/新北市/highest_temp
weather[[2]][[2]][[2]] # 明天/新北市/highest_temp
```

```{r}
weather[[1]][[2]]$highest_temp # 今天/新北市/highest_temp
weather[[2]][[2]]$highest_temp # 明天/新北市/highest_temp
```


## 新增/替換/刪除元素

**範例**
```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在: 替換
a[[4]] <- "7" # 元素不存在： 增加
a[c(5,6)] <- c("J", "K")
a
```

 *增加一個“Johnson”使用[[.]]<-。
 *使用前一章的向量疊代(recursive vector concatenate)法，新增一個“Mary”。
```{r}
a[[7]] <- "Johnson"
a
a <- c(a,c("Mary"))
```


```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    )
  )

str(list1)
```

```{r}
# 更改日期
list1[[1]]$birthday <- ymd("1997-03-21")

# 新增資料
list1[[2]] <- list(
  name="Mary",
  birthday=ymd("1998-08-24")
)

str(list1)
```

```{r}
list1[[2]]$`status` <- c(height=163, weight=45)
list1[[1]][[3]][["height"]] <- 176
str(list1)
```


```{r}
list1[[1]][["age"]] <- 21
list1[[2]]["age"] <- list(21)

# 改變「一個」時，使用[[ ]]比較不會錯。
str(list1)
```

